### ISSUE TITLE
Error starting riemann-dash

### ISSUE THREAD

**Issue by ivanshaovchev** [riemann/riemann-dash#82]
CentOS 6.5, Ruby 1.8.7, Gem 1.3.7, riemann-dash-0.2.9

[vagrant@vagrant-centos64 ~]$ riemann-dash
No configuration loaded; using defaults.
```
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/webrick-1.3.1/lib/webrick/httprequest.rb:302: nested *?+ in regexp: /^(\S+)\s+(\S++)(?:\s+HTTP\/(\d+\.\d+))?\r?\n/ (SyntaxError)
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/webrick-1.3.1/lib/webrick.rb:223
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler/webrick.rb:1
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:20:in `const_get'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:20:in `get'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:26:in `inject'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:20:in `each'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:20:in `inject'
	from /usr/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/handler.rb:20:in `get'
	from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.5/lib/sinatra/base.rb:1770:in `detect_rack_handler'
	from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.5/lib/sinatra/base.rb:1768:in `each'
	from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.5/lib/sinatra/base.rb:1768:in `detect_rack_handler'
	from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.5/lib/sinatra/base.rb:1429:in `run!'
	from /usr/lib/ruby/gems/1.8/gems/riemann-dash-0.2.9/bin/riemann-dash:7
	from /usr/bin/riemann-dash:19:in `load'
	from /usr/bin/riemann-dash:19
```

**Comment by mfournier** [comment]
Closing, as this is really a bug in a very old version of webrick. Not much we can do about it.
